import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.targets.js.webpack.KotlinWebpackConfig
import java.util.Properties

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    // alias(libs.plugins.androidApplication) // Disabled for desktop-focused development
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
    id("com.teamdev.jxbrowser") version "2.0.0"
}

// Load version from properties file
val versionPropsFile = file("../version.properties")
val versionProps = Properties()
if (versionPropsFile.exists()) {
    versionPropsFile.inputStream().use { 
        versionProps.load(it)
    }
}
val appVersion = versionProps.getProperty("app.version", "8.8.0")
val bundleVersion = versionProps.getProperty("app.bundle.version", "8.8.0")

println("📦 Building BOSS Version: $appVersion")

// Task to generate Version constants from properties
val generateVersionConstants = tasks.register("generateVersionConstants") {
    val outputDir = layout.buildDirectory.dir("generated/source/version")
    val outputFile = outputDir.map { it.file("ai/rever/boss/utils/VersionConstants.kt") }
    
    inputs.file(versionPropsFile)
    outputs.file(outputFile)
    
    doLast {
        val major = versionProps.getProperty("app.version.major", "8")
        val minor = versionProps.getProperty("app.version.minor", "8") 
        val patch = versionProps.getProperty("app.version.patch", "0")
        
        outputFile.get().asFile.apply {
            parentFile.mkdirs()
            writeText("""
                |package ai.rever.boss.utils
                |
                |/**
                | * Auto-generated version constants from version.properties
                | * Do not edit this file manually - it will be regenerated on build
                | */
                |internal object VersionConstants {
                |    const val MAJOR = $major
                |    const val MINOR = $minor
                |    const val PATCH = $patch
                |}
                |
            """.trimMargin())
        }
    }
}

repositories {
    google()
    mavenCentral()
    maven("https://packages.jetbrains.team/maven/p/ij/intellij-dependencies")
}

jxbrowser {
    version = "8.8.0" // JxBrowser version, not app version
}

kotlin {
    // Android target disabled for desktop-focused development
    /*
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }
    */
    
    // iOS targets disabled for desktop-focused development
    // Uncomment below if iOS support is needed in the future
    /*
    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
            
            // Export Decompose and Essenty for iOS
            export(libs.decompose)
            export(libs.essenty.lifecycle)
            export(libs.essenty.state.keeper)
        }
    }
    */
    
    jvm("desktop")
    
    // WASM targets disabled for desktop-focused development
    /*
    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        moduleName = "composeApp"
        browser {
            val rootDirPath = project.rootDir.path
            val projectDirPath = project.projectDir.path
            commonWebpackConfig {
                outputFileName = "composeApp.js"
                devServer = (devServer ?: KotlinWebpackConfig.DevServer()).apply {
                    static = (static ?: mutableListOf()).apply {
                        // Serve sources to debug inside browser
                        add(rootDirPath)
                        add(projectDirPath)
                    }
                }
            }
        }
        binaries.executable()
    }
    */
    
    sourceSets {
        val desktopMain by getting
        
        // Add generated source directory to commonMain
        commonMain {
            kotlin.srcDir(generateVersionConstants.map { it.outputs.files.singleFile.parent })
        }

        // androidMain.dependencies disabled for desktop-focused development
        /*
        androidMain.dependencies {
            implementation(compose.preview)
            implementation(libs.androidx.activity.compose)
        }
        */
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material)
            implementation(compose.materialIconsExtended)
            implementation(compose.ui)
            implementation(compose.components.resources)
            implementation(compose.components.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodel)
            implementation(libs.androidx.lifecycle.runtime.compose)
            implementation(projects.shared)
            implementation(libs.precompose)
//            implementation(libs.precompose.molecule)
            implementation(libs.precompose.viewmodel)

            // Decompose dependencies
            implementation(libs.decompose)
            implementation(libs.decompose.extensions.compose)
            implementation(libs.decompose.extensions.compose.experimental)
            implementation(libs.essenty.lifecycle)
            implementation(libs.essenty.state.keeper)
            implementation(libs.kotlinx.serialization.core)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.datetime)
            
            // Compose Icons dependencies
            implementation(libs.compose.icons.feather)
            implementation(libs.compose.icons.fontawesome)
            
            // Supabase dependencies
            implementation(libs.supabase.postgrest)
            implementation(libs.supabase.auth)
            implementation(libs.supabase.realtime)
            implementation(libs.supabase.storage)
            implementation(libs.supabase.functions)
        }
        desktopMain.dependencies {
            implementation(compose.desktop.currentOs)
            implementation(libs.kotlinx.coroutines.swing)
            implementation(compose.components.resources)
            
            // PTY4J with all required dependencies
            implementation(libs.pty4j)
            implementation(libs.purejavacomm) // Explicitly add this dependency
            implementation(libs.jna.platform) // JNA platform specific
            
            // For ANSI terminal emulation
            implementation(libs.lanterna)
            
            // Logging
            implementation(libs.slf4j.api)
            implementation(libs.slf4j.simple)
            
            // QR Code generation
            implementation(libs.zxing.core)
            implementation(libs.zxing.javase)
            
            // JxBrowser with Compose support
            implementation(jxbrowser.currentPlatform)
            implementation(jxbrowser.compose)
            
            // JavaCV for video recording - removed due to notarization issues
            // implementation("org.bytedeco:javacv-platform:1.5.11")
            
            // Ktor client for HTTP requests
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.cio)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)
        }
    }
}

// Android configuration disabled for desktop-focused development
/*
android {
    namespace = "ai.rever.boss"
    compileSdk = libs.versions.android.compileSdk.get().toInt()
    
    sourceSets {
        named("main") {
            manifest.srcFile("src/androidMain/AndroidManifest.xml")
            res.srcDirs("src/androidMain/res")
            // Don't include commonMain/resources in android resources
        }
    }
    
    defaultConfig {
        applicationId = "ai.rever.boss"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = 1
        versionName = "1.0"
    }
    buildFeatures {
        compose = true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = libs.versions.compose.compiler.get()
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    dependencies {
        debugImplementation(libs.compose.ui.tooling)
    }
}
*/

compose.desktop {
    application {
        mainClass = "ai.rever.boss.MainKt"
        
        // Enable building uber/fat JAR
        buildTypes.release.proguard {
            isEnabled.set(false)
        }
        
        // Specify JDK for native distributions - use OpenJDK 21 for better Apple Silicon support
        javaHome = System.getenv("JAVA_HOME") ?: "/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home"
        
        // JVM arguments optimized for Apple Silicon and hardened runtime
        jvmArgs(
            "-Djna.nosys=true",
            // These will be set at runtime, not build time
            "-Dpty4j.tmpdir=\${java.io.tmpdir}/boss-pty4j",
            // JCEF arguments
            "--add-opens=java.desktop/sun.awt=ALL-UNNAMED",
            "--add-opens=java.desktop/sun.lwawt=ALL-UNNAMED",
            "--add-opens=java.desktop/sun.lwawt.macosx=ALL-UNNAMED",
            "-Dapple.awt.application.appearance=system",
            // Apple Silicon JIT compatibility flags
            "-XX:+IgnoreUnrecognizedVMOptions"
        )
        
        nativeDistributions {
            targetFormats(
                TargetFormat.Dmg,           // macOS
                TargetFormat.Msi,           // Windows  
                TargetFormat.Deb,           // Linux - Ubuntu/Debian
                TargetFormat.Rpm            // Linux - RHEL/Fedora
                // Removed AppImage - not working reliably
                // JAR distribution handled separately via createExecutableJar task
            )
            packageName = "BOSS"
            packageVersion = appVersion
            description = "Business Operating System Service - Intelligent service automation platform"
            copyright = "© 2024 Risa Labs Inc. All rights reserved."
            vendor = "Risa Labs Inc."
            
            // Bundle a complete, self-contained JVM
            includeAllModules = true
            
            // Note: When includeAllModules is true, the modules() call is redundant
            // as all modules will be included. If you want to optimize size later,
            // set includeAllModules = false and specify only required modules:
            // modules("java.base", "java.desktop", "java.logging", "java.net.http", 
            //         "java.sql", "java.prefs", "java.scripting", "jdk.unsupported",
            //         "java.naming", "java.xml", "java.management", "jdk.crypto.ec")
            
            windows {
                menuGroup = "BOSS"
                upgradeUuid = "8a5a7659-2e0f-41bd-bbbb-3140b1e7dd7d"
                
                // Use Windows ICO format for proper MSI icon display
                iconFile.set(project.file("src/desktopMain/resources/boss_icon.ico"))
                
                // Windows code signing is handled by external tools (signtool.exe)
                // Configuration for MSI signing is done in the CI/CD pipeline
                
                // Configure Windows to accept command line arguments for deep links
                // The protocol registration is handled at runtime by WindowsProtocolHandler
                console = false  // Don't show console window
                dirChooser = true  // Allow user to choose install directory
                perUserInstall = true  // Install per-user to avoid admin requirements
                shortcut = true  // Create desktop shortcut
                menu = true  // Add to Start Menu
            }
            
            linux {
                packageName = "boss"
                debMaintainer = "support@risalabs.ai"
                menuGroup = "Development"
                iconFile.set(project.file("src/desktopMain/resources/boss_icon.png"))
            }
            
            macOS {
                bundleID = "ai.rever.boss"
                iconFile.set(project.file("src/desktopMain/resources/boss_icon.icns"))
                packageName = "BOSS"
                dmgPackageVersion = appVersion
                dmgPackageBuildVersion = "1"
                
                
                // Note: bundleJRE is not a valid property in current Compose Desktop
                // The JVM is automatically bundled when creating native distributions
                // Use includeAllModules = true above to ensure all JVM modules are included
                
                // Code signing configuration
                signing {
                    // Enable signing by default, disable only if explicitly skipped
                    val skipSigning = System.getenv("DISABLE_MACOS_SIGNING") == "true"
                    sign.set(!skipSigning)
                    
                    // Use environment variable for certificate identity, fallback to default
                    val developerId = System.getenv("MACOS_DEVELOPER_ID") 
                        ?: "Developer ID Application: Fnu Shivang (7X4CJM22GN)"
                    identity.set(developerId)
                    
                    // Debug logging
                    println("🔐 macOS Code Signing Configuration:")
                    println("   DISABLE_MACOS_SIGNING: ${System.getenv("DISABLE_MACOS_SIGNING")}")
                    println("   Identity: $developerId")
                    println("   Signing enabled: ${!skipSigning}")
                }
                
                // Entitlements
                entitlementsFile.set(project.file("src/desktopMain/resources/BOSS.entitlements"))
                
                // DMG customization
                infoPlist {
                    extraKeysRawXml = """
                        <key>LSMinimumSystemVersion</key>
                        <string>10.15</string>
                        <key>CFBundleShortVersionString</key>
                        <string>$appVersion</string>
                        <key>CFBundleVersion</key>
                        <string>$bundleVersion</string>
                        <key>NSHighResolutionCapable</key>
                        <true/>
                        <key>NSSupportsAutomaticGraphicsSwitching</key>
                        <true/>
                        <key>NSCameraUsageDescription</key>
                        <string>BOSS needs access to your camera for video conferencing and screen sharing.</string>
                        <key>NSMicrophoneUsageDescription</key>
                        <string>BOSS needs access to your microphone for video conferencing and voice communication.</string>
                        <key>CFBundleURLTypes</key>
                        <array>
                            <dict>
                                <key>CFBundleURLName</key>
                                <string>ai.rever.boss</string>
                                <key>CFBundleURLSchemes</key>
                                <array>
                                    <string>boss</string>
                                </array>
                            </dict>
                        </array>
                    """.trimIndent()
                }
            }
        }
    }
}

// Manually extract pty4j native libraries
tasks.register("extractPty4jNative") {
    doLast {
        val pty4jNativeDir = layout.buildDirectory.dir("pty4j-native").get().asFile
        val tmpDir = layout.buildDirectory.dir("tmp").get().asFile
        
        // Create directories
        pty4jNativeDir.mkdirs()
        tmpDir.mkdirs()
        
        // Find PTY4J jar in classpath
        val pty4jJar = project.configurations.getByName("desktopRuntimeClasspath").files.find { 
            it.name.startsWith("pty4j-") && it.name.endsWith(".jar")
        }
        
        if (pty4jJar != null) {
            println("Extracting from ${pty4jJar.name}")
            
            // Extract using built-in copy function
            copy {
                from(zipTree(pty4jJar)) {
                    include("**/native/**")
                }
                into(pty4jNativeDir)
                includeEmptyDirs = false
                
                eachFile {
                    // Remove the path prefix before 'native'
                    val nativeIndex = path.indexOf("native/")
                    if (nativeIndex >= 0) {
                        path = path.substring(nativeIndex + "native/".length)
                    }
                }
            }
            
            // Make native libraries executable
            pty4jNativeDir.walkTopDown().forEach { file ->
                if (file.isFile && (file.name.endsWith(".so") || file.name.endsWith(".dylib"))) {
                    file.setExecutable(true)
                }
            }
        } else {
            println("Warning: PTY4J jar not found in classpath")
        }
        
        // Print the extracted files for debugging
        println("Extracted PTY4J native libraries to: ${pty4jNativeDir.absolutePath}")
    }
}

// Sign PTY4J native binaries with hardened runtime for macOS notarization
tasks.register("signPty4jBinaries") {
    description = "Signs PTY4J native binaries with hardened runtime for Apple notarization"
    group = "build"
    
    // Only run on macOS and when signing is enabled
    onlyIf {
        val isMacOS = System.getProperty("os.name").lowercase().contains("mac")
        val signingDisabled = System.getenv("DISABLE_MACOS_SIGNING") == "true"
        isMacOS && !signingDisabled
    }
    
    doLast {
        println("🔧 Signing PTY4J native binaries with hardened runtime for notarization...")
        
        // Get developer identity from environment or use default
        val developerId = System.getenv("MACOS_DEVELOPER_ID") 
            ?: System.getenv("DEVELOPER_ID")
            ?: "Developer ID Application: Fnu Shivang (7X4CJM22GN)"
        
        // Find the built app in the standard Compose Desktop location
        val appDir = layout.buildDirectory.dir("compose/binaries/main/app").get().asFile
        val appFile = appDir.listFiles()?.find { it.name.endsWith(".app") }
        
        if (appFile?.exists() == true) {
            println("Found app: ${appFile.name}")
            
            // Find PTY4J jar inside the app
            val appContents = File(appFile, "Contents/app")
            val pty4jJar = appContents.listFiles()?.find { 
                it.name.startsWith("pty4j-") && it.name.endsWith(".jar")
            }
            
            if (pty4jJar?.exists() == true) {
                println("Processing PTY4J jar: ${pty4jJar.name}")
                
                // Create temporary directory for jar manipulation
                val tempDir = File(System.getProperty("java.io.tmpdir"), "pty4j-sign-${System.currentTimeMillis()}")
                tempDir.mkdirs()
                
                try {
                    // Extract the entire jar
                    exec {
                        workingDir = tempDir
                        commandLine("jar", "xf", pty4jJar.absolutePath)
                    }
                    
                    // Find and sign the native spawn helper binaries
                    val spawnHelpers = tempDir.walkTopDown().filter { 
                        it.name == "pty4j-unix-spawn-helper" && it.isFile 
                    }.toList()
                    
                    if (spawnHelpers.isNotEmpty()) {
                        println("Found ${spawnHelpers.size} PTY4J spawn helper binary(ies) to sign:")
                        
                        for (helper in spawnHelpers) {
                            println("  Signing: ${helper.relativeTo(tempDir)}")
                            
                            // Make executable
                            helper.setExecutable(true)
                            
                            // Sign with hardened runtime - critical for notarization
                            try {
                                exec {
                                    commandLine(
                                        "codesign", 
                                        "--force", 
                                        "--options", "runtime",
                                        "--sign", developerId,
                                        "--timestamp", 
                                        helper.absolutePath
                                    )
                                }
                                
                                // Verify signature
                                exec {
                                    commandLine("codesign", "-vv", helper.absolutePath)
                                }
                                
                                println("    ✅ Successfully signed ${helper.name}")
                            } catch (e: Exception) {
                                println("    ⚠️ Warning: Failed to sign ${helper.name}: ${e.message}")
                            }
                        }
                        
                        // Also sign any other native binaries in the jar
                        val otherNatives = tempDir.walkTopDown().filter { 
                            it.isFile && (it.name.endsWith(".dylib") || it.name.startsWith("libpty"))
                        }.toList()
                        
                        for (native in otherNatives) {
                            println("  Signing native library: ${native.relativeTo(tempDir)}")
                            native.setExecutable(true)
                            
                            try {
                                exec {
                                    commandLine(
                                        "codesign",
                                        "--force",
                                        "--options", "runtime",
                                        "--sign", developerId,
                                        "--timestamp",
                                        native.absolutePath
                                    )
                                }
                                println("    ✅ Successfully signed ${native.name}")
                            } catch (e: Exception) {
                                println("    ⚠️ Warning: Failed to sign ${native.name}: ${e.message}")
                            }
                        }
                        
                        // Recreate the jar with signed binaries
                        val signedJar = File(pty4jJar.parentFile, "${pty4jJar.nameWithoutExtension}-signed.jar")
                        exec {
                            workingDir = tempDir
                            commandLine("jar", "cf", signedJar.absolutePath, ".")
                        }
                        
                        // Replace original jar with signed version
                        pty4jJar.delete()
                        signedJar.renameTo(pty4jJar)
                        
                        println("✅ PTY4J natives signed with hardened runtime and jar updated")
                        
                        // Re-sign the main app bundle since we modified its contents
                        println("🔧 Re-signing main app bundle after PTY4J modifications...")
                        try {
                            exec {
                                commandLine(
                                    "codesign",
                                    "--force",
                                    "--options", "runtime",
                                    "--sign", developerId,
                                    "--timestamp",
                                    "--deep",
                                    appFile.absolutePath
                                )
                            }
                            
                            // Verify the main app signature
                            exec {
                                commandLine("codesign", "-vv", appFile.absolutePath)
                            }
                            
                            println("✅ Main app bundle re-signed successfully")
                        } catch (e: Exception) {
                            println("⚠️ Warning: Failed to re-sign main app bundle: ${e.message}")
                        }
                        
                    } else {
                        println("⚠️ Warning: No pty4j-unix-spawn-helper binaries found in jar")
                    }
                    
                } finally {
                    // Clean up temp directory
                    tempDir.deleteRecursively()
                }
                
            } else {
                println("⚠️ Warning: PTY4J jar not found in app bundle")
            }
        } else {
            println("⚠️ Warning: Built app not found at expected location")
        }
    }
}

// Extract JCEF natives
tasks.register("extractJcefNatives") {
    doLast {
        val jcefNativeDir = layout.buildDirectory.dir("jcef-natives").get().asFile
        jcefNativeDir.mkdirs()
        
        // The jcefmaven library will download natives automatically
        // We just need to ensure the directory exists
        println("JCEF natives directory: ${jcefNativeDir.absolutePath}")
    }
}

// Configure task dependencies for PTY4J signing and DMG packaging
afterEvaluate {
    // Make run tasks depend on the extraction tasks
    tasks.findByName("run")?.apply {
        dependsOn("extractPty4jNative")
        dependsOn("extractJcefNatives")
    }
    
    // Make signPty4jBinaries run after createDistributable but before packageDmg
    tasks.findByName("signPty4jBinaries")?.apply {
        mustRunAfter("createDistributable")
    }
    
    // Make packaging tasks depend on PTY4J signing (only on macOS with signing enabled)
    tasks.findByName("packageDmg")?.apply {
        val isMacOS = System.getProperty("os.name").lowercase().contains("mac")
        val signingDisabled = System.getenv("DISABLE_MACOS_SIGNING") == "true"
        
        if (isMacOS && !signingDisabled) {
            dependsOn("signPty4jBinaries")
            println("📝 packageDmg will depend on signPty4jBinaries for macOS with signing enabled")
        }
    }
    
    // Also make sure any other packaging tasks depend on signing if needed
    tasks.findByName("createDistributable")?.apply {
        finalizedBy("signPty4jBinaries")
    }
}

// Task to create an executable JAR
tasks.register<Jar>("createExecutableJar") {
    dependsOn("desktopJar")
    group = "build"
    description = "Creates an executable JAR with all dependencies"
    
    archiveClassifier.set("all")
    archiveBaseName.set("BOSS")
    archiveVersion.set(appVersion as String)
    destinationDirectory.set(layout.buildDirectory.dir("libs"))
    
    // Get the desktop jar output
    val desktopJar = tasks.named<Jar>("desktopJar").get()
    
    // Include the main jar contents
    from(zipTree(desktopJar.archiveFile.get().asFile))
    
    // Include all runtime dependencies
    from(configurations.named("desktopRuntimeClasspath").get().map { 
        if (it.isDirectory) it else zipTree(it) 
    }) {
        exclude("META-INF/*.SF")
        exclude("META-INF/*.DSA")
        exclude("META-INF/*.RSA")
        exclude("META-INF/MANIFEST.MF")
        exclude("module-info.class")
    }
    
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    
    manifest {
        attributes(mapOf(
            "Main-Class" to "ai.rever.boss.MainKt",
            "Implementation-Title" to "BOSS",
            "Implementation-Version" to appVersion,
            "Implementation-Vendor" to "Risa Labs Inc.",
            "Multi-Release" to "true"
        ))
    }
}

// Task to package JAR with native libraries
tasks.register<Zip>("packageJarWithNatives") {
    dependsOn("createExecutableJar", "extractJcefNatives", "extractPty4jNative")
    group = "build"
    description = "Creates a distributable package with JAR and native libraries"
    
    archiveBaseName.set("BOSS-package")
    archiveVersion.set(appVersion as String)
    archiveExtension.set("zip")
    destinationDirectory.set(layout.buildDirectory.dir("distributions"))
    
    // Include the executable JAR
    from(layout.buildDirectory.dir("libs")) {
        include("BOSS-$appVersion-all.jar")
        into("")
    }
    
    // Include native libraries
    from(layout.buildDirectory.dir("jcef-natives")) {
        into("jcef-natives")
    }
    from(layout.buildDirectory.dir("pty4j-native")) {
        into("pty4j-native")
    }
    
    // Include launch scripts
    from(projectDir) {
        include("launch.sh", "launch.bat")
        into("")
    }
}

// Ensure version constants are generated before Kotlin compilation
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    dependsOn(generateVersionConstants)
}
