import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.targets.js.webpack.KotlinWebpackConfig
import java.util.Properties
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    // alias(libs.plugins.androidApplication) // Disabled for desktop-focused development
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
    id("com.teamdev.jxbrowser") version "2.0.0"
}

// Load version from properties file
val versionPropsFile = file("../version.properties")
val versionProps = Properties()
if (versionPropsFile.exists()) {
    versionPropsFile.inputStream().use { 
        versionProps.load(it)
    }
}
val appVersion = versionProps.getProperty("app.version", "8.8.0")
val bundleVersion = versionProps.getProperty("app.bundle.version", "8.8.0")

println("📦 Building BOSS Version: $appVersion")

// Task to generate Version constants from properties
val generateVersionConstants = tasks.register("generateVersionConstants") {
    val outputDir = layout.buildDirectory.dir("generated/source/version")
    val outputFile = outputDir.map { it.file("ai/rever/boss/utils/VersionConstants.kt") }

    inputs.file(versionPropsFile)
    outputs.file(outputFile)

    // CRITICAL: Force regeneration on every build to prevent stale version constants
    // This prevents Issue #111 where builds had wrong version embedded in artifacts
    outputs.upToDateWhen { false }

    doLast {
        val major = versionProps.getProperty("app.version.major", "8")
        val minor = versionProps.getProperty("app.version.minor", "8")
        val patch = versionProps.getProperty("app.version.patch", "0")

        outputFile.get().asFile.apply {
            parentFile.mkdirs()
            writeText("""
                |package ai.rever.boss.utils
                |
                |/**
                | * Auto-generated version constants from version.properties
                | * Do not edit this file manually - it will be regenerated on build
                | */
                |internal object VersionConstants {
                |    const val MAJOR = $major
                |    const val MINOR = $minor
                |    const val PATCH = $patch
                |}
                |
            """.trimMargin())
        }
    }
}

// Task to generate versioned CLI scripts from templates
val generateVersionedCLIScripts = tasks.register("generateVersionedCLIScripts") {
    val sourceDir = file("../scripts")
    val outputDir = layout.buildDirectory.dir("generated/resources/cli")

    inputs.dir(sourceDir)
    inputs.file(versionPropsFile)
    outputs.dir(outputDir)

    // Force regeneration on every build to keep CLI version synchronized
    outputs.upToDateWhen { false }

    doLast {
        val version = appVersion
        val buildDate = LocalDateTime.now().format(
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")
        )

        outputDir.get().asFile.mkdirs()

        sourceDir.listFiles()?.forEach { scriptFile ->
            if (scriptFile.isFile && (scriptFile.name == "boss" || scriptFile.name.startsWith("boss."))) {
                val content = scriptFile.readText()
                val versioned = content
                    .replace("{{VERSION}}", version)
                    .replace("{{BUILD_DATE}}", buildDate)

                val outputFile = outputDir.get().asFile.resolve(scriptFile.name)
                outputFile.writeText(versioned)

                // Preserve executable permission for bash script
                if (scriptFile.name == "boss") {
                    outputFile.setExecutable(true, false)
                }

                println("Generated versioned CLI script: ${scriptFile.name} (v$version)")
            }
        }
    }
}

repositories {
    google()
    mavenCentral()
    maven("https://packages.jetbrains.team/maven/p/ij/intellij-dependencies")
}

jxbrowser {
    version = "8.8.0" // JxBrowser version, not app version
}

kotlin {
    // Android target disabled for desktop-focused development
    /*
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }
    */

    // iOS targets disabled for desktop-focused development
    // Uncomment below if iOS support is needed in the future
    /*
    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true

            // Export Decompose and Essenty for iOS
            export(libs.decompose)
            export(libs.essenty.lifecycle)
            export(libs.essenty.state.keeper)
        }
    }
    */

    jvm("desktop")

    // Enable experimental time API
    sourceSets.all {
        languageSettings.optIn("kotlin.time.ExperimentalTime")
    }
    
    // WASM targets disabled for desktop-focused development
    /*
    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        moduleName = "composeApp"
        browser {
            val rootDirPath = project.rootDir.path
            val projectDirPath = project.projectDir.path
            commonWebpackConfig {
                outputFileName = "composeApp.js"
                devServer = (devServer ?: KotlinWebpackConfig.DevServer()).apply {
                    static = (static ?: mutableListOf()).apply {
                        // Serve sources to debug inside browser
                        add(rootDirPath)
                        add(projectDirPath)
                    }
                }
            }
        }
        binaries.executable()
    }
    */
    
    sourceSets {
        val desktopMain by getting
        val desktopTest by getting

        // Add generated source directory to commonMain
        commonMain {
            kotlin.srcDir(generateVersionConstants.map { it.outputs.files.singleFile.parent })
        }

        // Add generated CLI scripts to desktopMain resources
        // Note: srcDir needs parent directory to maintain /cli/ path structure
        desktopMain.resources.srcDir(generateVersionedCLIScripts.map { it.outputs.files.singleFile.parentFile })

        // androidMain.dependencies disabled for desktop-focused development
        /*
        androidMain.dependencies {
            implementation(compose.preview)
            implementation(libs.androidx.activity.compose)
        }
        */
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material)
            implementation(compose.materialIconsExtended)
            implementation(compose.ui)
            implementation(compose.components.resources)
            implementation(compose.components.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodel)
            implementation(libs.androidx.lifecycle.runtime.compose)
            implementation(projects.shared)
            implementation(libs.precompose)
//            implementation(libs.precompose.molecule)
            implementation(libs.precompose.viewmodel)

            // Decompose dependencies
            implementation(libs.decompose)
            implementation(libs.decompose.extensions.compose)
            implementation(libs.decompose.extensions.compose.experimental)
            implementation(libs.essenty.lifecycle)
            implementation(libs.essenty.state.keeper)
            implementation(libs.kotlinx.serialization.core)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.datetime)
            
            // Compose Icons dependencies
            implementation(libs.compose.icons.feather)
            implementation(libs.compose.icons.fontawesome)
            
            // Supabase dependencies
            implementation(libs.supabase.postgrest)
            implementation(libs.supabase.auth)
            implementation(libs.supabase.realtime)
            implementation(libs.supabase.storage)
            implementation(libs.supabase.functions)
        }
        desktopMain.dependencies {
            implementation(compose.desktop.currentOs)
            implementation(libs.kotlinx.coroutines.swing)
            implementation(compose.components.resources)
            
            // PTY4J with all required dependencies
            implementation(libs.pty4j)
            implementation(libs.purejavacomm) // Explicitly add this dependency
            implementation(libs.jna.platform) // JNA platform specific
            
            // For ANSI terminal emulation
            implementation(libs.lanterna)
            
            // Logging
            implementation(libs.slf4j.api)
            implementation(libs.slf4j.simple)
            
            // QR Code generation
            implementation(libs.zxing.core)
            implementation(libs.zxing.javase)
            
            // JxBrowser with Compose and Swing support
            implementation(jxbrowser.currentPlatform)
            implementation(jxbrowser.compose)
            implementation(jxbrowser.swing)
            
            // JavaCV for video recording - removed due to notarization issues
            // implementation("org.bytedeco:javacv-platform:1.5.11")
            
            // Ktor client for HTTP requests
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.cio)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)

            // CLI argument parsing
            implementation("com.github.ajalt.clikt:clikt:4.2.1")
        }

        desktopTest.dependencies {
            implementation(kotlin("test-junit5"))
            implementation("org.junit.jupiter:junit-jupiter:5.10.0")
        }
    }
}


compose.desktop {
    application {
        mainClass = "ai.rever.boss.MainKt"
        
        // Enable building uber/fat JAR
        buildTypes.release.proguard {
            isEnabled.set(false)
        }
        
        // Specify JDK for native distributions - use OpenJDK 21 for better Apple Silicon support
        javaHome = System.getenv("JAVA_HOME") ?: "/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home"
        
        // JVM arguments optimized for Apple Silicon and hardened runtime
        jvmArgs(
            "-Djna.nosys=true",
            // These will be set at runtime, not build time
            "-Dpty4j.tmpdir=\${java.io.tmpdir}/boss-pty4j",
            // JCEF arguments
            "--add-opens=java.desktop/sun.awt=ALL-UNNAMED",
            "--add-opens=java.desktop/sun.lwawt=ALL-UNNAMED",
            "--add-opens=java.desktop/sun.lwawt.macosx=ALL-UNNAMED",
            "-Dapple.awt.application.appearance=system",
            // Apple Silicon JIT compatibility flags
            "-XX:+IgnoreUnrecognizedVMOptions"
        )
        
        nativeDistributions {
            targetFormats(
                TargetFormat.Dmg,           // macOS
                TargetFormat.Msi,           // Windows  
                TargetFormat.Deb,           // Linux - Ubuntu/Debian
                TargetFormat.Rpm            // Linux - RHEL/Fedora
                // Removed AppImage - not working reliably
                // JAR distribution handled separately via createExecutableJar task
            )
            packageName = "BOSS"
            packageVersion = appVersion
            description = "Business Operating System Service - Intelligent service automation platform"
            copyright = "© 2024 Risa Labs Inc. All rights reserved."
            vendor = "Risa Labs Inc."
            
            // Bundle a complete, self-contained JVM
            includeAllModules = true
            
            // Note: When includeAllModules is true, the modules() call is redundant
            // as all modules will be included. If you want to optimize size later,
            // set includeAllModules = false and specify only required modules:
            // modules("java.base", "java.desktop", "java.logging", "java.net.http", 
            //         "java.sql", "java.prefs", "java.scripting", "jdk.unsupported",
            //         "java.naming", "java.xml", "java.management", "jdk.crypto.ec")
            
            windows {
                menuGroup = "BOSS"
                upgradeUuid = "8a5a7659-2e0f-41bd-bbbb-3140b1e7dd7d"
                
                // Use Windows ICO format for proper MSI icon display
                iconFile.set(project.file("src/desktopMain/resources/boss_icon.ico"))
                
                // Windows code signing is handled by external tools (signtool.exe)
                // Configuration for MSI signing is done in the CI/CD pipeline
                
                // Configure Windows to accept command line arguments for deep links
                // The protocol registration is handled at runtime by WindowsProtocolHandler
                console = false  // Don't show console window
                dirChooser = true  // Allow user to choose install directory
                perUserInstall = true  // Install per-user to avoid admin requirements
                shortcut = true  // Create desktop shortcut
                menu = true  // Add to Start Menu
            }
            
            linux {
                packageName = "boss"
                debMaintainer = "support@risalabs.ai"
                menuGroup = "Development"
                iconFile.set(project.file("src/desktopMain/resources/boss_icon.png"))
            }
            
            macOS {
                bundleID = "ai.rever.boss"
                iconFile.set(project.file("src/desktopMain/resources/boss_icon.icns"))
                packageName = "BOSS"
                dmgPackageVersion = appVersion
                dmgPackageBuildVersion = "1"
                
                
                // Note: bundleJRE is not a valid property in current Compose Desktop
                // The JVM is automatically bundled when creating native distributions
                // Use includeAllModules = true above to ensure all JVM modules are included
                
                // Code signing configuration
                signing {
                    // Enable signing by default, disable only if explicitly skipped
                    val skipSigning = System.getenv("DISABLE_MACOS_SIGNING") == "true"
                    sign.set(!skipSigning)
                    
                    // Use environment variable for certificate identity, fallback to default
                    val developerId = System.getenv("MACOS_DEVELOPER_ID") 
                        ?: "Developer ID Application: Fnu Shivang (7X4CJM22GN)"
                    identity.set(developerId)
                    
                    // Debug logging
                    println("🔐 macOS Code Signing Configuration:")
                    println("   DISABLE_MACOS_SIGNING: ${System.getenv("DISABLE_MACOS_SIGNING")}")
                    println("   Identity: $developerId")
                    println("   Signing enabled: ${!skipSigning}")
                }
                
                // Entitlements
                entitlementsFile.set(project.file("src/desktopMain/resources/BOSS.entitlements"))
                
                // DMG customization
                infoPlist {
                    extraKeysRawXml = """
                        <key>LSMinimumSystemVersion</key>
                        <string>10.15</string>
                        <key>CFBundleShortVersionString</key>
                        <string>$appVersion</string>
                        <key>CFBundleVersion</key>
                        <string>$bundleVersion</string>
                        <key>NSHighResolutionCapable</key>
                        <true/>
                        <key>NSSupportsAutomaticGraphicsSwitching</key>
                        <true/>
                        <key>NSCameraUsageDescription</key>
                        <string>BOSS needs access to your camera for video conferencing and screen sharing.</string>
                        <key>NSMicrophoneUsageDescription</key>
                        <string>BOSS needs access to your microphone for video conferencing and voice communication.</string>
                        <key>CFBundleURLTypes</key>
                        <array>
                            <dict>
                                <key>CFBundleURLName</key>
                                <string>ai.rever.boss</string>
                                <key>CFBundleURLSchemes</key>
                                <array>
                                    <string>boss</string>
                                    <string>http</string>
                                    <string>https</string>
                                </array>
                            </dict>
                        </array>
                        <key>CFBundleDocumentTypes</key>
                        <array>
                            <dict>
                                <key>CFBundleTypeName</key>
                                <string>HTML Document</string>
                                <key>CFBundleTypeRole</key>
                                <string>Viewer</string>
                                <key>LSItemContentTypes</key>
                                <array>
                                    <string>public.html</string>
                                    <string>public.url</string>
                                </array>
                            </dict>
                        </array>
                    """.trimIndent()
                }
            }
        }
    }
}

// ============================================================================
// Application Run Tasks with Environment Configuration
// ============================================================================

// Simple wrapper task to run with local Supabase configuration
tasks.register("runLocal") {
    group = "application"
    description = "Run desktop application with local Supabase configuration (localhost:54321)"
    dependsOn("run")
}

// Simple wrapper task to run with production Supabase configuration
tasks.register("runProduction") {
    group = "application"
    description = "Run desktop application with production Supabase configuration (api.risaboss.com)"
    dependsOn("run")
}

// Configure run task based on which wrapper task will execute
// This runs after task graph is built but before execution
gradle.taskGraph.whenReady {
    if (gradle.taskGraph.hasTask(":composeApp:runLocal")) {
        println("🏠 Running BOSS with LOCAL Supabase configuration")
        println()
        println("Configuration:")
        println("  SUPABASE_URL: http://localhost:54321")
        println("  SUPABASE_ANON_KEY: sb_publishable_ACJWlzQHlZjBrEguHvfOxg_3BJgxAaH")
        println("  SUPABASE_FUNCTION_URL: http://localhost:54321/functions/v1")
        println("  (System properties will override local.properties)")
        println()

        tasks.named<JavaExec>("run") {
            systemProperty("SUPABASE_URL", "http://localhost:54321")
            systemProperty("SUPABASE_ANON_KEY", "sb_publishable_ACJWlzQHlZjBrEguHvfOxg_3BJgxAaH")
            systemProperty("SUPABASE_FUNCTION_URL", "http://localhost:54321/functions/v1")
        }
    } else if (gradle.taskGraph.hasTask(":composeApp:runProduction")) {
        println("☁️  Running BOSS with PRODUCTION Supabase configuration")
        println()
        println("Configuration:")
        println("  SUPABASE_URL: https://api.risaboss.com")
        println("  SUPABASE_FUNCTION_URL: https://api.risaboss.com/functions/v1")
        println("  (System properties will override local.properties)")
        println()

        tasks.named<JavaExec>("run") {
            systemProperty("SUPABASE_URL", "https://api.risaboss.com")
            systemProperty("SUPABASE_ANON_KEY", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjbndxYW1xZG5zYWRyYW51Zmp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMDUwMzMsImV4cCI6MjA3NDY4MTAzM30.WZ6jSKuqM2EMyZLgoGJnI8Bn_Sdwk6plW0PkVNLIYVY")
            systemProperty("SUPABASE_FUNCTION_URL", "https://api.risaboss.com/functions/v1")
        }
    }
}

// ============================================================================
// Native Library Extraction Tasks
// ============================================================================

// Manually extract pty4j native libraries
tasks.register("extractPty4jNative") {
    doLast {
        val pty4jNativeDir = layout.buildDirectory.dir("pty4j-native").get().asFile
        val tmpDir = layout.buildDirectory.dir("tmp").get().asFile
        
        // Create directories
        pty4jNativeDir.mkdirs()
        tmpDir.mkdirs()
        
        // Find PTY4J jar in classpath
        val pty4jJar = project.configurations.getByName("desktopRuntimeClasspath").files.find { 
            it.name.startsWith("pty4j-") && it.name.endsWith(".jar")
        }
        
        if (pty4jJar != null) {
            println("Extracting from ${pty4jJar.name}")
            
            // Extract using built-in copy function
            copy {
                from(zipTree(pty4jJar)) {
                    include("**/native/**")
                }
                into(pty4jNativeDir)
                includeEmptyDirs = false
                
                eachFile {
                    // Remove the path prefix before 'native'
                    val nativeIndex = path.indexOf("native/")
                    if (nativeIndex >= 0) {
                        path = path.substring(nativeIndex + "native/".length)
                    }
                }
            }
            
            // Make native libraries executable
            pty4jNativeDir.walkTopDown().forEach { file ->
                if (file.isFile && (file.name.endsWith(".so") || file.name.endsWith(".dylib"))) {
                    file.setExecutable(true)
                }
            }
        } else {
            println("Warning: PTY4J jar not found in classpath")
        }
        
        // Print the extracted files for debugging
        println("Extracted PTY4J native libraries to: ${pty4jNativeDir.absolutePath}")
    }
}

// Sign PTY4J native binaries with hardened runtime for macOS notarization
tasks.register("signPty4jBinaries") {
    description = "Signs PTY4J native binaries with hardened runtime for Apple notarization"
    group = "build"
    
    // Only run on macOS and when signing is enabled
    onlyIf {
        val isMacOS = System.getProperty("os.name").lowercase().contains("mac")
        val signingDisabled = System.getenv("DISABLE_MACOS_SIGNING") == "true"
        isMacOS && !signingDisabled
    }
    
    doLast {
        println("🔧 Signing PTY4J native binaries with hardened runtime for notarization...")
        
        // Get developer identity from environment or use default
        val developerId = System.getenv("MACOS_DEVELOPER_ID") 
            ?: System.getenv("DEVELOPER_ID")
            ?: "Developer ID Application: Fnu Shivang (7X4CJM22GN)"
        
        // Find the built app in the standard Compose Desktop location
        val appDir = layout.buildDirectory.dir("compose/binaries/main/app").get().asFile
        val appFile = appDir.listFiles()?.find { it.name.endsWith(".app") }
        
        if (appFile?.exists() == true) {
            println("Found app: ${appFile.name}")
            
            // Find PTY4J jar inside the app
            val appContents = File(appFile, "Contents/app")
            val pty4jJar = appContents.listFiles()?.find { 
                it.name.startsWith("pty4j-") && it.name.endsWith(".jar")
            }
            
            if (pty4jJar?.exists() == true) {
                println("Processing PTY4J jar: ${pty4jJar.name}")
                
                // Create temporary directory for jar manipulation
                val tempDir = File(System.getProperty("java.io.tmpdir"), "pty4j-sign-${System.currentTimeMillis()}")
                tempDir.mkdirs()
                
                try {
                    // Extract the entire jar
                    project.exec {
                        workingDir = tempDir
                        commandLine("jar", "xf", pty4jJar.absolutePath)
                    }
                    
                    // Sign PTY4J native libraries with hardened runtime
                    val nativeFiles = tempDir.walkTopDown().filter { 
                        it.isFile && (it.name.endsWith(".dylib") || it.name.contains("spawn-helper"))
                    }.toList()
                    
                    if (nativeFiles.isNotEmpty()) {
                        println("Found ${nativeFiles.size} PTY4J native binary(ies) to sign:")
                        
                        for (nativeFile in nativeFiles) {
                            println("  Signing: ${nativeFile.relativeTo(tempDir)}")
                            
                            // Make executable
                            nativeFile.setExecutable(true)
                            
                            // Sign with hardened runtime
                            try {
                                project.exec {
                                    commandLine(
                                        "codesign",
                                        "--force",
                                        "--options", "runtime",
                                        "--sign", developerId,
                                        "--timestamp",
                                        nativeFile.absolutePath
                                    )
                                }

                                // Verify signature
                                project.exec {
                                    commandLine("codesign", "-vv", nativeFile.absolutePath)
                                }
                                
                                println("    ✅ Successfully signed ${nativeFile.name}")
                            } catch (e: Exception) {
                                println("    ⚠️ Warning: Failed to sign ${nativeFile.name}: ${e.message}")
                            }
                        }
                        
                        // Recreate the jar with signed native libraries
                        val signedJar = File(pty4jJar.parentFile, "${pty4jJar.nameWithoutExtension}-signed.jar")
                        project.exec {
                            workingDir = tempDir
                            commandLine("jar", "cf", signedJar.absolutePath, ".")
                        }

                        // Replace original jar with signed version
                        pty4jJar.delete()
                        signedJar.renameTo(pty4jJar)

                        println("✅ PTY4J jar updated with signed native libraries")

                    } else {
                        println("⚠️ Warning: No PTY4J native binaries found in jar")
                    }

                } finally {
                    // Clean up temp directory
                    tempDir.deleteRecursively()
                }

                // CRITICAL: Re-sign the entire app bundle after modifying the JAR
                println("🔒 Re-signing app bundle after PTY4J modifications...")
                try {
                    project.exec {
                        commandLine(
                            "codesign",
                            "--force",
                            "--deep",
                            "--options", "runtime",
                            "--sign", developerId,
                            "--timestamp",
                            "--entitlements", project.file("src/desktopMain/resources/BOSS.entitlements").absolutePath,
                            appFile.absolutePath
                        )
                    }

                    // Verify the re-signed app
                    project.exec {
                        commandLine("codesign", "-vvv", "--deep", "--strict", appFile.absolutePath)
                    }

                    println("✅ App bundle re-signed successfully")
                } catch (e: Exception) {
                    println("❌ Failed to re-sign app bundle: ${e.message}")
                    throw e
                }

            } else {
                println("⚠️ Warning: PTY4J jar not found in app bundle")
            }
        } else {
            println("⚠️ Warning: Built app not found at expected location")
        }
    }
}

// Extract JCEF natives
tasks.register("extractJcefNatives") {
    doLast {
        val jcefNativeDir = layout.buildDirectory.dir("jcef-natives").get().asFile
        jcefNativeDir.mkdirs()

        // The jcefmaven library will download natives automatically
        // We just need to ensure the directory exists
        println("JCEF natives directory: ${jcefNativeDir.absolutePath}")
    }
}

// Extract CLI script to app bundle Resources for Homebrew installation
tasks.register("extractCLIToAppResources") {
    description = "Extracts CLI script to BOSS.app/Contents/Resources for Homebrew binary stanza"
    group = "build"

    // Only run on macOS
    onlyIf {
        System.getProperty("os.name").lowercase().contains("mac")
    }

    doLast {
        println("📦 Extracting CLI script to app bundle Resources...")

        // Check if signing is enabled
        val signingDisabled = System.getenv("DISABLE_MACOS_SIGNING") == "true"
        val developerId = System.getenv("MACOS_DEVELOPER_ID")
            ?: System.getenv("DEVELOPER_ID")
            ?: "Developer ID Application: Fnu Shivang (7X4CJM22GN)"

        // Find the built app in the standard Compose Desktop location
        val appDir = layout.buildDirectory.dir("compose/binaries/main/app").get().asFile
        val appFile = appDir.listFiles()?.find { it.name.endsWith(".app") }

        if (appFile?.exists() == true) {
            println("Found app: ${appFile.name}")

            // Target location: BOSS.app/Contents/Resources/
            val resourcesDir = File(appFile, "Contents/Resources")
            resourcesDir.mkdirs()

            // Source: generated CLI script from build/generated/resources/cli/boss
            val generatedCLIDir = layout.buildDirectory.dir("generated/resources/cli").get().asFile
            val cliScript = File(generatedCLIDir, "boss")

            if (cliScript.exists()) {
                val targetScript = File(resourcesDir, "boss")

                // Copy the CLI script
                cliScript.copyTo(targetScript, overwrite = true)

                // Make it executable
                targetScript.setExecutable(true, false)

                println("✅ CLI script installed to: ${targetScript.absolutePath}")
                println("   Homebrew will symlink this to /opt/homebrew/bin/boss")

                // CRITICAL: Re-sign the entire app bundle after adding the CLI script
                // This is necessary because adding files to a signed bundle invalidates the signature
                if (!signingDisabled) {
                    println("🔒 Re-signing app bundle after CLI script installation...")
                    try {
                        project.exec {
                            commandLine(
                                "codesign",
                                "--force",
                                "--deep",
                                "--options", "runtime",
                                "--sign", developerId,
                                "--timestamp",
                                "--entitlements", project.file("src/desktopMain/resources/BOSS.entitlements").absolutePath,
                                appFile.absolutePath
                            )
                        }

                        // Verify the re-signed app
                        project.exec {
                            commandLine("codesign", "-vvv", "--deep", "--strict", appFile.absolutePath)
                        }

                        println("✅ App bundle re-signed successfully after CLI script installation")
                    } catch (e: Exception) {
                        println("❌ Failed to re-sign app bundle: ${e.message}")
                        throw e
                    }
                } else {
                    println("⚠️  Signing disabled - skipping app bundle re-signing")
                }
            } else {
                println("⚠️  Warning: Generated CLI script not found at ${cliScript.absolutePath}")
                println("   Make sure generateVersionedCLIScripts task ran successfully")
            }
        } else {
            println("⚠️  Warning: Built app not found at ${appDir.absolutePath}")
            println("   This task should run after createDistributable")
        }
    }
}

// Configure task dependencies for PTY4J signing and DMG packaging
afterEvaluate {
    // Make run tasks depend on the extraction tasks
    tasks.findByName("run")?.apply {
        dependsOn("extractPty4jNative")
        dependsOn("extractJcefNatives")
    }

    val isMacOS = System.getProperty("os.name").lowercase().contains("mac")
    val signingDisabled = System.getenv("DISABLE_MACOS_SIGNING") == "true"

    // Make signPty4jBinaries run AFTER createDistributable and BEFORE any signing/packaging
    tasks.findByName("signPty4jBinaries")?.apply {
        mustRunAfter("createDistributable")
        // Must run before the Compose Desktop signing tasks
        tasks.findByName("signApp")?.mustRunAfter(this)
        tasks.findByName("signUberJarProvisionedRuntime")?.mustRunAfter(this)
    }

    // CRITICAL: Make createDistributable finalize with signPty4jBinaries
    // This ensures PTY4J natives are signed before Compose Desktop signs the whole app
    tasks.findByName("createDistributable")?.apply {
        if (isMacOS && !signingDisabled) {
            finalizedBy("signPty4jBinaries")
            println("📝 createDistributable will be finalized by signPty4jBinaries")
        }
        // Always extract CLI script to app Resources on macOS (for Homebrew installation)
        if (isMacOS) {
            finalizedBy("extractCLIToAppResources")
            println("📝 createDistributable will be finalized by extractCLIToAppResources")
        }
    }

    // Make sure signing happens before packaging
    tasks.findByName("packageDmg")?.apply {
        if (isMacOS && !signingDisabled) {
            mustRunAfter("signPty4jBinaries")
            tasks.findByName("signApp")?.let { mustRunAfter(it) }
            tasks.findByName("signUberJarProvisionedRuntime")?.let { mustRunAfter(it) }
            println("📝 packageDmg will run after PTY4J signing and app signing")
        }
    }
}

// Task to create an executable JAR
tasks.register<Jar>("createExecutableJar") {
    dependsOn("desktopJar")
    group = "build"
    description = "Creates an executable JAR with all dependencies"
    
    archiveClassifier.set("all")
    archiveBaseName.set("BOSS")
    archiveVersion.set(appVersion as String)
    destinationDirectory.set(layout.buildDirectory.dir("libs"))
    
    // Get the desktop jar output
    val desktopJar = tasks.named<Jar>("desktopJar").get()
    
    // Include the main jar contents
    from(zipTree(desktopJar.archiveFile.get().asFile))
    
    // Include all runtime dependencies
    from(configurations.named("desktopRuntimeClasspath").get().map { 
        if (it.isDirectory) it else zipTree(it) 
    }) {
        exclude("META-INF/*.SF")
        exclude("META-INF/*.DSA")
        exclude("META-INF/*.RSA")
        exclude("META-INF/MANIFEST.MF")
        exclude("module-info.class")
    }
    
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    
    manifest {
        attributes(mapOf(
            "Main-Class" to "ai.rever.boss.MainKt",
            "Implementation-Title" to "BOSS",
            "Implementation-Version" to appVersion,
            "Implementation-Vendor" to "Risa Labs Inc.",
            "Multi-Release" to "true"
        ))
    }
}

// Task to package JAR with native libraries
tasks.register<Zip>("packageJarWithNatives") {
    dependsOn("createExecutableJar", "extractJcefNatives", "extractPty4jNative")
    group = "build"
    description = "Creates a distributable package with JAR and native libraries"
    
    archiveBaseName.set("BOSS-package")
    archiveVersion.set(appVersion as String)
    archiveExtension.set("zip")
    destinationDirectory.set(layout.buildDirectory.dir("distributions"))
    
    // Include the executable JAR
    from(layout.buildDirectory.dir("libs")) {
        include("BOSS-$appVersion-all.jar")
        into("")
    }
    
    // Include native libraries
    from(layout.buildDirectory.dir("jcef-natives")) {
        into("jcef-natives")
    }
    from(layout.buildDirectory.dir("pty4j-native")) {
        into("pty4j-native")
    }
    
    // Include launch scripts
    from(projectDir) {
        include("launch.sh", "launch.bat")
        into("")
    }
}

// Ensure version constants are generated before Kotlin compilation
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    dependsOn(generateVersionConstants)
}

// Wrapper tasks that auto-increment build number before packaging
tasks.register("packageDmgWithIncrement") {
    group = "distribution"
    description = "Builds DMG package with auto-incremented build number"

    doFirst {
        // Execute auto-increment before packaging
        rootProject.tasks.findByName("autoIncrementBuildNumber")?.actions?.forEach {
            it.execute(rootProject.tasks.getByName("autoIncrementBuildNumber"))
        }
    }

    finalizedBy("packageDmg")
}

tasks.register("packageMsiWithIncrement") {
    group = "distribution"
    description = "Builds MSI package with auto-incremented build number"

    doFirst {
        rootProject.tasks.findByName("autoIncrementBuildNumber")?.actions?.forEach {
            it.execute(rootProject.tasks.getByName("autoIncrementBuildNumber"))
        }
    }

    finalizedBy("packageMsi")
}

tasks.register("createExecutableJarWithIncrement") {
    group = "build"
    description = "Creates executable JAR with auto-incremented build number"

    doFirst {
        rootProject.tasks.findByName("autoIncrementBuildNumber")?.actions?.forEach {
            it.execute(rootProject.tasks.getByName("autoIncrementBuildNumber"))
        }
    }

    finalizedBy("createExecutableJar")
}
