apiVersion: v1
data:
  ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY2FsaG9zdCIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNjQ1NzY0MjcyLCJleHAiOjE5NjExNDAyNzJ9.mfBxOvZpOLQfhEuwMOmtKRN3PYhm3H5-b8lSzUfSLEQ
  DATABASE_URL: postgres://supabase_admin:SuperSecurePassword123@postgres:5432/postgres
  ENABLE_IMAGE_TRANSFORMATION: "true"
  FILE_SIZE_LIMIT: "52428800"
  FILE_STORAGE_BACKEND_PATH: /var/lib/storage
  GLOBAL_S3_BUCKET: stub
  IMGPROXY_URL: http://supabase-imgproxy:5001
  PGRST_JWT_SECRET: your-jwt-secret-at-least-32-characters-long
  POSTGREST_URL: http://supabase-rest:3000
  REGION: stub
  SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY2FsaG9zdCIsInJvbGUiOiJzZXJ2aWNlX3JvbGUiLCJpYXQiOjE2NDU3NjQyNzIsImV4cCI6MTk2MTE0MDI3Mn0.V7fmSY9T8jJwYgRKE1lnG3wy6ygcgvP3HJ8M-2QLkJ4
  STORAGE_BACKEND: file
  TENANT_ID: stub
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"ANON_KEY":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY2FsaG9zdCIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNjQ1NzY0MjcyLCJleHAiOjE5NjExNDAyNzJ9.mfBxOvZpOLQfhEuwMOmtKRN3PYhm3H5-b8lSzUfSLEQ","DATABASE_URL":"postgres://supabase_admin:your-postgres-password-change-me@postgres:5432/postgres","ENABLE_IMAGE_TRANSFORMATION":"true","FILE_SIZE_LIMIT":"52428800","FILE_STORAGE_BACKEND_PATH":"/var/lib/storage","GLOBAL_S3_BUCKET":"stub","IMGPROXY_URL":"http://supabase-imgproxy:5001","PGRST_JWT_SECRET":"your-jwt-secret-at-least-32-characters-long","POSTGREST_URL":"http://supabase-rest:3000","REGION":"stub","SERVICE_KEY":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY2FsaG9zdCIsInJvbGUiOiJzZXJ2aWNlX3JvbGUiLCJpYXQiOjE2NDU3NjQyNzIsImV4cCI6MTk2MTE0MDI3Mn0.V7fmSY9T8jJwYgRKE1lnG3wy6ygcgvP3HJ8M-2QLkJ4","STORAGE_BACKEND":"file","TENANT_ID":"stub"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"supabase","component":"storage"},"name":"supabase-storage-config","namespace":"default"}}
  creationTimestamp: "2025-08-09T04:01:55Z"
  labels:
    app: supabase
    component: storage
  name: supabase-storage-config
  namespace: default
  resourceVersion: "1754712812629263022"
  uid: 06e584d4-1473-41ae-a662-f7384272f603
