#Auto-incremented patch version
#Tue Jan 27 09:31:41 UTC 2026
app.version.major=8
app.build.date=2026-01-27
app.version.patch=15
app.release.notes.url=https\://github.com/risa-labs-inc/BossConsole-Releases/releases/tag/v8.9.0
app.bundle.version=8.16.15
app.version.minor=16
app.release.channel=stable
app.version=8.16.15
app.build.number=1
app.prerelease.suffix=
