#Auto-incremented patch version
#Wed Nov 19 04:54:23 UTC 2025
app.version.major=8
app.build.date=2025-11-19
app.version.patch=20
app.release.notes.url=https\://github.com/risa-labs-inc/BOSS-Releases/releases/tag/v8.9.0
app.bundle.version=8.13.20
app.version.minor=13
app.release.channel=stable
app.version=8.13.20
app.build.number=1
