#Auto-incremented patch version
#Wed Jul 30 10:08:14 UTC 2025
app.version.major=8
app.build.date=2025-07-30
app.version.patch=4
app.release.notes.url=https\://github.com/risa-labs-inc/BOSS-Releases/releases/tag/v8.9.0
app.bundle.version=8.9.4
app.version.minor=9
app.release.channel=stable
app.version=8.9.4
app.build.number=1
