apiVersion: v1
data:
  GOTRUE_DB_DATABASE_URL: cG9zdGdyZXM6Ly9zdXBhYmFzZV9hZG1pbjpTdXBlclNlY3VyZVBhc3N3b3JkMTIzQHBvc3RncmVzOjU0MzIvcG9zdGdyZXM/c3NsbW9kZT1kaXNhYmxl
  GOTRUE_JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1hdC1sZWFzdC0zMi1jaGFyYWN0ZXJzLWxvbmctZm9yLXByb2R1Y3Rpb24=
  GOTRUE_OPERATOR_TOKEN: c3VwZXItc2VjcmV0LW9wZXJhdG9yLXRva2VuLWNoYW5nZS1tZS1pbi1wcm9kdWN0aW9u
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"app":"supabase","component":"auth"},"name":"supabase-auth-secrets","namespace":"default"},"stringData":{"GOTRUE_DB_DATABASE_URL":"postgres://supabase_admin:SuperSecurePassword123@postgres:5432/postgres?sslmode=disable","GOTRUE_JWT_SECRET":"your-super-secret-jwt-key-at-least-32-characters-long-for-production","GOTRUE_OPERATOR_TOKEN":"super-secret-operator-token-change-me-in-production"},"type":"Opaque"}
  creationTimestamp: "2025-08-09T03:47:23Z"
  labels:
    app: supabase
    component: auth
  name: supabase-auth-secrets
  namespace: default
  resourceVersion: "1754711243821439004"
  uid: 7ab05267-3cf2-4a58-806e-04e862fa8ccb
type: Opaque
