apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"supabase-studio"},"name":"supabase-studio","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"supabase-studio"}},"template":{"metadata":{"labels":{"app":"supabase-studio"}},"spec":{"containers":[{"env":[{"name":"SUPABASE_URL","value":"http://34.9.47.213"},{"name":"SUPABASE_REST_URL","value":"http://34.66.84.207"},{"name":"SUPABASE_AUTH_URL","value":"http://34.9.246.150"},{"name":"SUPABASE_STORAGE_URL","value":"http://34.67.139.68"},{"name":"SUPABASE_REALTIME_URL","value":"ws://34.42.189.31"},{"name":"SUPABASE_META_URL","value":"http://34.58.246.78"},{"name":"SUPABASE_FUNCTIONS_URL","value":"http://34.68.96.199"},{"name":"SUPABASE_ANON_KEY","value":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY2FsaG9zdCIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNjQ1NzY0MjcyLCJleHAiOjE5NjExNDAyNzJ9.mfBxOvZpOLQfhEuwMOmtKRN3PYhm3H5-b8lSzUfSLEQ"},{"name":"SUPABASE_SERVICE_KEY","value":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY2FsaG9zdCIsInJvbGUiOiJzZXJ2aWNlX3JvbGUiLCJpYXQiOjE2NDU3NjQyNzIsImV4cCI6MTk2MTE0MDI3Mn0.V7fmSY9T8jJwYgRKE1lnG3wy6ygcgvP3HJ8M-2QLkJ4"},{"name":"POSTGRES_HOST","value":"35.225.71.65"},{"name":"POSTGRES_PORT","value":"5432"},{"name":"POSTGRES_DB","value":"postgres"},{"name":"POSTGRES_USER","value":"supabase_admin"},{"name":"POSTGRES_PASSWORD","value":"SuperSecurePassword123"},{"name":"STUDIO_PG_META_URL","value":"http://34.58.246.78"},{"name":"PUBLIC_URL","value":"http://34.9.47.213"}],"image":"supabase/studio:latest","name":"studio","ports":[{"containerPort":3000}]}]}}}}
  creationTimestamp: "2025-08-09T09:15:49Z"
  generation: 8
  labels:
    app: supabase-studio
  name: supabase-studio
  namespace: default
  resourceVersion: "1754785068227119003"
  uid: 6d0fa0e1-3454-4989-8955-4def72b7b293
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: supabase-studio
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-08-09T05:35:09-07:00"
      creationTimestamp: null
      labels:
        app: supabase-studio
    spec:
      containers:
      - env:
        - name: SUPABASE_URL
          value: http://34.9.47.213
        - name: SUPABASE_REST_URL
          value: http://34.9.47.213
        - name: SUPABASE_AUTH_URL
          value: http://34.9.47.213
        - name: SUPABASE_STORAGE_URL
          value: http://34.67.139.68
        - name: SUPABASE_REALTIME_URL
          value: ws://34.42.189.31
        - name: SUPABASE_META_URL
          value: http://34.58.246.78
        - name: SUPABASE_FUNCTIONS_URL
          value: http://34.9.47.213
        - name: SUPABASE_SERVICE_KEY
          value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY2FsaG9zdCIsInJvbGUiOiJzZXJ2aWNlX3JvbGUiLCJpYXQiOjE3NTQ3ODUwNTQsImV4cCI6MTc4NjMyMTA1NH0.leOWOgwHUKaKgNTtmKO5W6Y6OdpFQyxhzFE9bEhI41E
        - name: SUPABASE_ANON_KEY
          value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY2FsaG9zdCIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzU0Nzg1MDU0LCJleHAiOjE3ODYzMjEwNTR9.UR-amMvudG2h3iBBzBfRPjH6psOhyWYrrq3yhc_s-s4
        - name: POSTGRES_HOST
          value: 35.225.71.65
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: supabase_admin
        - name: POSTGRES_PASSWORD
          value: SuperSecurePassword123
        - name: STUDIO_PG_META_URL
          value: http://34.58.246.78
        - name: PUBLIC_URL
          value: http://34.9.47.213
        image: supabase/studio:latest
        imagePullPolicy: IfNotPresent
        name: studio
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-08-09T09:17:31Z"
    lastUpdateTime: "2025-08-09T09:17:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-08-09T09:15:49Z"
    lastUpdateTime: "2025-08-10T00:17:48Z"
    message: ReplicaSet "supabase-studio-569d8cdf5c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 8
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
