apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"supabase","component":"rest"},"name":"supabase-rest","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"supabase","component":"rest"}},"template":{"metadata":{"labels":{"app":"supabase","component":"rest"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"supabase-rest-config"}},{"secretRef":{"name":"supabase-rest-secrets"}}],"image":"postgrest/postgrest:v12.0.2","livenessProbe":{"httpGet":{"path":"/","port":3000},"initialDelaySeconds":30,"periodSeconds":30,"timeoutSeconds":10},"name":"postgrest","ports":[{"containerPort":3000,"name":"http"}],"readinessProbe":{"httpGet":{"path":"/","port":3000},"initialDelaySeconds":10,"periodSeconds":10,"timeoutSeconds":5},"resources":{"limits":{"cpu":"1000m","memory":"1Gi"},"requests":{"cpu":"250m","memory":"256Mi"}}}],"initContainers":[{"command":["sh","-c","until pg_isready -h postgres -p 5432; do sleep 2; done;"],"image":"postgres:15","name":"wait-for-postgres"}]}}}}
  creationTimestamp: "2025-08-09T03:58:14Z"
  generation: 1
  labels:
    app: supabase
    component: rest
  name: supabase-rest
  namespace: default
  resourceVersion: "1754711909651983022"
  uid: 16819e58-cc27-4a91-8370-14009e24cc09
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: supabase
      component: rest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: supabase
        component: rest
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: supabase-rest-config
        - secretRef:
            name: supabase-rest-secrets
        image: postgrest/postgrest:v12.0.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: postgrest
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - until pg_isready -h postgres -p 5432; do sleep 2; done;
        image: postgres:15
        imagePullPolicy: IfNotPresent
        name: wait-for-postgres
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-08-09T03:58:29Z"
    lastUpdateTime: "2025-08-09T03:58:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-08-09T03:58:14Z"
    lastUpdateTime: "2025-08-09T03:58:29Z"
    message: ReplicaSet "supabase-rest-649f57c56" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
