apiVersion: v1
data:
  DB_PASSWORD: eW91ci1wb3N0Z3Jlcy1wYXNzd29yZC1jaGFuZ2UtbWU=
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWF0LWxlYXN0LTMyLWNoYXJhY3RlcnMtbG9uZw==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"app":"supabase","component":"realtime"},"name":"supabase-realtime-secrets","namespace":"default"},"stringData":{"DB_PASSWORD":"your-postgres-password-change-me","JWT_SECRET":"your-jwt-secret-at-least-32-characters-long"},"type":"Opaque"}
  creationTimestamp: "2025-08-09T04:00:58Z"
  labels:
    app: supabase
    component: realtime
  name: supabase-realtime-secrets
  namespace: default
  resourceVersion: "1754712929586639013"
  uid: 323909a7-115e-4319-9551-d0053b550892
type: Opaque
