apiVersion: v1
data:
  API_EXTERNAL_URL: https://api.risaboss.com
  GOTRUE_API_EXTERNAL_URL: https://api.risaboss.com
  GOTRUE_API_HOST: 0.0.0.0
  GOTRUE_API_PORT: "9999"
  GOTRUE_DB_DRIVER: postgres
  GOTRUE_DISABLE_SIGNUP: "false"
  GOTRUE_EMAIL_CONFIRM_CHANGES: "true"
  GOTRUE_EMAIL_DOUBLE_CONFIRM_CHANGES: "true"
  GOTRUE_EMAIL_ENABLE_SIGNUP: "true"
  GOTRUE_ENABLE_SIGNUP: "true"
  GOTRUE_JWT_ADMIN_ROLES: service_role
  GOTRUE_JWT_AUD: authenticated
  GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
  GOTRUE_JWT_EXP: "3600"
  GOTRUE_LOG_LEVEL: info
  GOTRUE_MAILER_SUBJECTS_CONFIRMATION: Confirm your BOSS account
  GOTRUE_MAILER_SUBJECTS_INVITE: You have been invited to BOSS
  GOTRUE_MAILER_SUBJECTS_RECOVERY: Reset your BOSS password
  GOTRUE_MFA_ENABLED: "true"
  GOTRUE_MFA_MAX_ENROLLED_FACTORS: "10"
  GOTRUE_SECURITY_UPDATE_PASSWORD_REQUIRE_REAUTHENTICATION: "true"
  GOTRUE_SITE_URL: boss://auth/verify
  GOTRUE_SMTP_HOST: smtp.gmail.com
  GOTRUE_SMTP_PASS: HjYZXRRGHNhW5nK&
  GOTRUE_SMTP_PORT: "587"
  GOTRUE_SMTP_USER: noreply.boss@risalabs.ai
  GOTRUE_URI_ALLOW_LIST: boss://auth/verify,http://localhost:3000
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"API_EXTERNAL_URL":"http://localhost:9999","GOTRUE_API_EXTERNAL_URL":"http://localhost:9999","GOTRUE_API_HOST":"0.0.0.0","GOTRUE_API_PORT":"9999","GOTRUE_DB_DRIVER":"postgres","GOTRUE_DISABLE_SIGNUP":"false","GOTRUE_EMAIL_CONFIRM_CHANGES":"true","GOTRUE_EMAIL_DOUBLE_CONFIRM_CHANGES":"true","GOTRUE_EMAIL_ENABLE_SIGNUP":"true","GOTRUE_ENABLE_SIGNUP":"true","GOTRUE_JWT_ADMIN_ROLES":"service_role","GOTRUE_JWT_AUD":"authenticated","GOTRUE_JWT_DEFAULT_GROUP_NAME":"authenticated","GOTRUE_JWT_EXP":"3600","GOTRUE_LOG_LEVEL":"info","GOTRUE_MFA_ENABLED":"true","GOTRUE_MFA_MAX_ENROLLED_FACTORS":"10","GOTRUE_SECURITY_UPDATE_PASSWORD_REQUIRE_REAUTHENTICATION":"true","GOTRUE_SITE_URL":"boss://auth/verify","GOTRUE_URI_ALLOW_LIST":"boss://auth/verify,http://localhost:3000"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"supabase","component":"auth"},"name":"supabase-auth-config","namespace":"default"}}
  creationTimestamp: "2025-08-09T03:47:08Z"
  labels:
    app: supabase
    component: auth
  name: supabase-auth-config
  namespace: default
  resourceVersion: "1754777882398031023"
  uid: 9cf6fe14-0fd7-4b51-9cef-97804106f515
